# I am a workflow that demonstrates how to output the different context objects

name: Variables and Context

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true

env:
  VAR1: Global1
  VAR2: Global2
  VAR3: Global3

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  job1:
    runs-on: ubuntu-latest 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      
  #step/job output variables
  job2:
    runs-on: ubuntu-latest
    
    outputs:
      output1: ${{ steps.step1.outputs.step1value }}
      output2: ${{ steps.step2.outputs.step2value }}
    
    steps:
      - name: Step 1
        id: step1
        # run: echo "::set-output name=step1value::hello"
        run: echo "step1value=Step1value" >> $GITHUB_OUTPUT

      - name: Step 2
        id: step2
        # run: echo "::set-output name=step2value::world"
        run: echo "step2value=step2value"  >> $GITHUB_OUTPUT
  
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo ${{needs.job2.outputs.output1}} ${{needs.job2.outputs.output2}}

  # access/set env variables
  job4:
    runs-on: ubuntu-latest
    env:
      VAR2: job4myvar2 in an job local variable
      VAR3: job4var3 local variables
    steps:

      - run: |
          echo "VAR1 at the end" 
          echo $VAR1
          echo ${{env.VAR1}}

          echo ""

          echo: "2 in the end"
          echo $VAR2

          echo "var3 end"
          echo $VAR3
        env:

        echo "var3 updated but not printed"
          VAR3: mystepvar3
