# I am a workflow that demonstrates how to output the different context objects

name: Variables and Context

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true

env:
  VAR1: Global1
  VAR2: Global2
  VAR3: Global3

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

  job2:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.step1value }}
      output2: ${{ steps.step2.outputs.step2value }}
    steps:
      - name: Step 1
        id: step1
        run: echo "step1value=Step1value" >> $GITHUB_OUTPUT

      - name: Step 2
        id: step2
        run: echo "step2value=step2value" >> $GITHUB_OUTPUT

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo ${{ needs.job2.outputs.output1 }} ${{ needs.job2.outputs.output2 }}

  job4:
    runs-on: ubuntu-latest
    env:
      VAR2: job4myvar2 in a job local variable
      VAR3: job4var3 local variables
    steps:
      - name: Print variables
        run: |
          echo "VAR1 at the end"
          echo "$VAR1"
          echo "${{ env.VAR1 }}"

          echo ""
          echo "VAR2 in the end"
          echo "$VAR2"

          echo "VAR3 end"
          echo "$VAR3"
        env:
          VAR3: mystepvar3
